apiVersion: v1
kind: Secret
metadata:
  name: bridge-postgres-secret
  namespace: bridge-platform
type: Opaque
data:
  POSTGRES_USER: YnJpZGdlX3VzZXI=  # bridge_user
  POSTGRES_PASSWORD: YnJpZGdlX3Bhc3N3b3Jk  # bridge_password
  POSTGRES_DB: YnJpZGdlX2Ri  # bridge_db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: bridge-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-postgres
  namespace: bridge-platform
  labels:
    app: bridge-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-postgres
  template:
    metadata:
      labels:
        app: bridge-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bridge-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bridge-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: bridge-postgres-secret
              key: POSTGRES_DB
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - bridge_user
              - -d
              - bridge_db
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - bridge_user
              - -d
              - bridge_db
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bridge-postgres
  namespace: bridge-platform
  labels:
    app: bridge-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: bridge-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: bridge-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-redis
  namespace: bridge-platform
  labels:
    app: bridge-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-redis
  template:
    metadata:
      labels:
        app: bridge-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command:
          - redis-server
          - --appendonly
          - "yes"
          - --maxmemory
          - "1gb"
          - --maxmemory-policy
          - "allkeys-lru"
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bridge-redis
  namespace: bridge-platform
  labels:
    app: bridge-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: bridge-redis